Add the Chapter_02 examples
EvanHahn/Express.js-in-Action-code pull request #8
Opened 2018-03-15 18:21 UTC by mikeshhoffman

2018-03-15 18:29 UTC, mikeshhoffman commented
Copied from printed book, ran, and tested.

2018-03-22 15:45 UTC, EvanHahn requested changes
I'd prefer to omit anything where it's not a project, but rather a single file. For example, that'd mean that `random-integer` would stay but `hello` wouldn't. Could you remove directories where there's just one file?

I also left one small comment about a change to some Chapter 3 code.

2018-03-22 15:45 UTC, EvanHahn commented on Chapter_03/guestbook/views/index.ejs
> +        <%= entry.body %>
This looks extraneous. Could you remove it from the PR?

2018-03-22 18:42 UTC, EvanHahn approved these changes

2018-03-22 18:42 UTC, merged